theme: minima

title: "Polarity-resolved imaging reveals active transport in catalytic Janus nanomotors"
description: "Code and data accompanying the ChemRxiv manuscript."

url: "https://jamalilab.github.io"
baseurl: "/Catalytic_Janus_Nanomotor"

show_excerpts: false
